"""Build the local decks from curated, WordNet-verified English lemmas.

Run: python3 tools/prepare_words.py /path/to/WordNet-3.0.tar.gz
No dictionary definitions are bundled. No network is used by this script or the app.
"""
import json
import pathlib
import sys
import tarfile
from extra_words import EXTRA_WORDS
from word_exclusions import EXCLUDED_WORDS

ROOT = pathlib.Path(__file__).resolve().parents[1]
DATA = ROOT / 'data'
DATA.mkdir(exist_ok=True)

# Candidate words are editorial selections; only actual WordNet entries survive.
CANDIDATES = {
    'food': '''apple apricot avocado banana blackberry blueberry cherry coconut cranberry date fig grape grapefruit guava kiwi lemon lime mango melon nectarine orange papaya peach pear pineapple plum pomegranate raspberry strawberry tangerine watermelon almond cashew chestnut hazelnut peanut pecan pistachio walnut bean beet broccoli cabbage carrot cauliflower celery corn cucumber eggplant garlic ginger leek lettuce mushroom onion pea pepper potato pumpkin radish spinach squash tomato turnip zucchini artichoke asparagus olive bread bagel baguette biscuit bun cereal cracker croissant dough flour noodle oatmeal pancake pasta pretzel rice sandwich toast tortilla waffle barley oat wheat butter cheese cream custard egg honey jam jelly margarine milk mustard oil salt sugar syrup vinegar yogurt bacon beef chicken ham lamb meat pork sausage steak turkey veal anchovy clam cod crab lobster mussel oyster salmon sardine shrimp squid tuna cake candy caramel chocolate cookie doughnut frosting icecream muffin pastry pie pudding tart vanilla coffee juice lemonade milkshake smoothie soda tea water cocoa cinnamon clove cumin nutmeg paprika parsley rosemary thyme basil mint oregano ketchup mayonnaise pickle salad soup stew sauce gravy pizza burger lasagna omelet quiche risotto sushi taco curry dumpling meatball popcorn chip crisps fudge marshmallow peanutbutter sesame lentil chickpea couscous tofu cheesecake shortbread sourdough meringue truffle caviar granola molasses porridge appetizer breakfast lunch dinner dessert snack picnic barbecue buffet bakery recipe menu chef kitchen spoon fork knife bowl plate cup bottle napkin chopstick saucepan kettle blender oven toaster whisk grill fryingpan dough topping crust feast roast peel slice crumb seed syrup frosting jam''',
    'animals': '''aardvark alligator alpaca ant anteater antelope ape armadillo baboon badger bat bear beaver bee beetle bison boar buffalo butterfly camel canary caterpillar cat cheetah chicken chimpanzee chinchilla clam cobra cockroach cod cougar cow coyote crab crane cricket crocodile crow deer dog dolphin donkey dove dragonfly duck eagle eel elephant elk emu falcon ferret finch firefly flamingo flea fly fox frog gazelle gecko gerbil giraffe goat goldfish goose gorilla grasshopper gull hamster hare hawk hedgehog heron hippopotamus hornet horse hummingbird hyena ibis iguana impala jackal jaguar jellyfish kangaroo kingfisher kitten koala ladybird ladybug lamb lemur leopard lion lizard lobster locust lynx llama magpie manatee meerkat mole mongoose monkey moose moth mouse mule mussel narwhal newt octopus opossum orangutan ostrich otter owl ox oyster panda panther parakeet parrot peacock pelican penguin pheasant pig pigeon platypus polar fox pony porcupine possum prawn puffin puma puppy quail rabbit raccoon ram rat raven reindeer rhinoceros robin rooster salamander salmon sardine scorpion seahorse seal shark sheep shrimp skunk sloth snail snake sparrow spider squirrel squid starfish stork swan tadpole termite tiger toad tortoise toucan trout tuna turkey turtle vulture walrus wasp weasel whale wolf wombat woodpecker worm yak zebra pet nest feather fur claw beak paw hoof horn tusk whisker wing tail egg shell flock herd hive burrow habitat aquarium zoo safari leash collar saddle kennel stable cocoon web venom camouflage migration hibernation predator prey reptile mammal insect amphibian wildlife''',
    'body': '''ankle arm artery back beard belly bladder blood bone brain breast breath cheek chest chin collarbone ear elbow eyelash eyebrow eyelid face finger fingernail fist foot forehead gum hair hand head heart heel hip intestine jaw joint kidney knee knuckle leg lip liver lung mouth muscle nail neck nerve nose nostril palm pelvis rib scalp shoulder skeleton skin skull spine stomach sweat tendon thigh throat thumb toe toenail tongue tooth torso vein waist wrist abdomen appendix cartilage diaphragm eardrum esophagus kneecap ligament pancreas pupil retina shin spleen sternum tonsil vertebra biceps triceps calf cranium iris molar incisor wisdom saliva sinus pulse fingerprint heartbeat breath sneeze hiccup yawn cough blink smile frown wrinkle dimple freckle bruise scar blister goosebump tear vision hearing smell taste touch balance digestion circulation reflex oxygen vitamin calcium protein immune posture exercise sleep fatigue hunger thirst pain ache fever shiver cramp fracture sprain bandage plaster thermometer stethoscope vaccine medicine dentist doctor surgeon nurse patient ambulance hospital clinic pharmacy wheelchair crutch cast infection recovery health anatomy skeleton''',
    'geography': '''Africa Antarctica Asia Europe Australia America England Scotland Wales Ireland France Spain Portugal Italy Germany Greece Austria Belgium Denmark Sweden Norway Finland Iceland Poland Hungary Romania Bulgaria Croatia Serbia Albania Switzerland Netherlands Luxembourg Russia Ukraine Belarus Estonia Latvia Lithuania Turkey Cyprus Malta Canada Mexico Brazil Argentina Chile Peru Colombia Ecuador Venezuela Uruguay Paraguay Bolivia Panama Cuba Jamaica Haiti Bahamas Honduras Nicaragua Guatemala Belize Morocco Egypt Algeria Tunisia Libya Sudan Ethiopia Somalia Kenya Uganda Tanzania Rwanda Burundi Nigeria Ghana Senegal Mali Niger Chad Cameroon Congo Angola Zambia Zimbabwe Botswana Namibia Mozambique Madagascar Mauritius Seychelles India China Japan Korea Thailand Vietnam Cambodia Laos Malaysia Singapore Indonesia Philippines Pakistan Bangladesh Nepal Bhutan Mongolia Afghanistan Iran Iraq Israel Jordan Lebanon Syria Yemen Oman Qatar Bahrain Kuwait Saudi Arabia Taiwan Greenland Fiji Samoa Tonga Vanuatu Haiti Belize Spain London Paris Rome Berlin Madrid Lisbon Athens Vienna Prague Warsaw Budapest Dublin Oslo Stockholm Helsinki Moscow Tokyo Beijing Shanghai Bangkok Seoul Delhi Mumbai Cairo Nairobi Lagos Sydney Melbourne Toronto Vancouver Montreal Boston Chicago Miami Seattle Denver Dallas Houston Phoenix Atlanta Amsterdam Venice Florence Naples Barcelona Seville Zurich Geneva Edinburgh Glasgow Belfast Liverpool Manchester Oxford Cambridge York Brussels Copenhagen Jerusalem Baghdad Tehran Istanbul desert island mountain river ocean lake valley beach forest jungle glacier volcano canyon waterfall cave coast continent country city village capital harbor peninsula reef meadow hill plateau dune oasis delta equator latitude longitude compass map atlas border region tundra prairie savanna rainforest bay gulf summit cliff shore lagoon archipelago''',
    'kids': '''apple banana orange pear peach grape lemon cherry melon strawberry carrot potato tomato onion cucumber pumpkin corn pea bean bread butter cheese milk egg rice pasta pizza sandwich pancake waffle cookie cake chocolate candy honey jam juice water cereal soup salad banana dog cat horse cow pig sheep goat chicken duck goose rabbit mouse rat hamster fish shark whale dolphin seal turtle frog snake lizard spider ant bee butterfly ladybug worm snail bird owl eagle parrot penguin lion tiger bear monkey elephant giraffe zebra kangaroo panda fox wolf deer squirrel bat crab octopus starfish pet tail paw wing feather nest egg shell tree flower grass leaf root seed plant bush forest jungle garden beach ocean river lake mountain hill island rain snow wind cloud rainbow storm thunder lightning sun moon star sky earth planet space rocket astronaut day night morning evening spring summer autumn winter house room door window wall roof floor bed pillow blanket sofa chair table desk lamp clock mirror carpet curtain bath shower sink toilet kitchen bedroom bathroom stairs key lock book pencil pen paper crayon ruler eraser scissors glue paint brush picture drawing toy doll ball kite balloon block puzzle game chess card marble teddy bicycle scooter skateboard swing slide sandbox school teacher student friend family mother father sister brother baby child grandfather grandmother uncle aunt cousin birthday party gift candle music song dance drum guitar piano bell bus car truck train boat ship plane helicopter wheel road bridge traffic station shop park zoo farm castle tent flag crown pirate treasure dragon monster robot fairy giant princess knight superhero smile laugh cry hug kiss clap jump run walk swim fly sleep dream read write count sing play climb bake build clean open close hot cold warm cool big small tall short long round square triangle circle red blue green yellow pink purple brown black white gold silver happy sad funny brave kind soft hard loud quiet fast slow hand foot head face hair ear eye nose mouth tooth tongue arm leg finger thumb knee elbow shoulder heart stomach back skin''',
    'teens': '''adventure ambition astronaut athlete audience backpack battery bicycle biology birthday blog bracelet calendar camera camping captain castle champion charity chemistry cinema circus classroom climate comedy concert costume courage creativity detective diary dinosaur disaster discovery drama dream earthquake eclipse electricity energy engine envelope escape exam experiment festival firefighter flashlight friendship future galaxy game goalkeeper graduation gravity guitar gymnastics helmet hero history hobby holiday homework horizon imagination internet invention island jacket journalist journey justice keyboard knowledge laboratory language laptop library lighthouse magazine marathon mathematics memory message meteor microscope mystery nature nightmare novel orchestra passport pattern photograph planet platform poetry pollution portrait practice puzzle quiz racket radio rainforest recipe referee rehearsal rescue robot rocket rollercoaster satellite science scooter sculpture season shadow skateboard smartphone snowflake soccer spaceship stadium strategy submarine suitcase sunglasses sunshine superhero telescope temperature theater tournament tradition trampoline travel treasure triangle universe vacation volcano weather website wilderness wizard workshop avalanche bamboo canyon carnival coral crystal diamond fossil glacier harbor hurricane iceberg jungle lagoon lightning magnet maze mountain museum network ocean orbit oxygen perfume pirate pyramid rainbow rhythm safari sandwich skyscraper snowboarding software starfish stopwatch sunrise sunset thunder traffic waterfall wildlife accordion acoustic arrow astronomy balloon bargain basketball bowling camping canoe chess competition compass confidence constellation conversation earthquake explorer fashion fountain geography greenhouse helicopter identity illusion ingredient instrument interview journalism landscape microphone mirror motorcycle museum navigation notebook parachute photography picnic popcorn pottery recycling reflection responsibility rhythm sailboat skating snowboard solar squirrel surfboard swimmer technology telescope tennis ticket tourism transport trumpet umbrella violin volleyball waterfall wisdom wristwatch yogurt''',
    'everyday': '''anchor apron attic axe backpack basket bench blanket broom bucket button candle carpet chain chair chimney clock coat comb cushion curtain diamond domino drawer drum fence flashlight fountain frame garage gate glove hammer hanger hat helmet hose jar key ladder lantern lawn lawnmower magnet mailbox marble mattress mirror mop needle necklace newspaper notebook paint pillow pipe pocket postcard poster purse ribbon ring rope rug ruler scarf scissors screw shelf shovel soap sock sponge spoon stamp stapler string suitcase sweater telephone thread towel umbrella uniform vase wallet watch wheel whistle window zipper acrobat actor angel architect artist astronaut author baker barber builder captain carpenter cashier chef cleaner coach dancer dentist detective doctor driver engineer farmer firefighter gardener guide judge librarian lifeguard magician mechanic musician nurse painter pilot plumber poet police reporter sailor scientist singer soldier surgeon tailor teacher waiter writer acorn autumn avalanche bamboo bark branch breeze cactus cave clay cliff cloud coal coral crystal dew dirt drought dust earthquake eclipse field fire flame flood fog fossil frost galaxy glacier gold granite hail horizon hurricane iceberg jungle lava lightning meadow mist moon moss mud ocean pebble planet pond rain rainbow reef river rock sand shadow shell snow snowflake soil spring star stone storm stream summer sunrise sunset swamp thunder tide tornado tree valley volcano waterfall wave wind winter wood account address agreement alarm answer balance beauty beginning belief birthday chance choice clue color comfort company courage dance danger decision dream effort emotion ending experience faith freedom friendship future gift happiness hope idea imagination invitation joke journey kindness laughter luck magic memory mistake mystery noise number opinion order patience peace promise question reason respect rhythm secret silence surprise thought time truth victory voice wish wonder work'''
}

for category, words in EXTRA_WORDS.items():
    CANDIDATES[category] += ' ' + words

with tarfile.open(sys.argv[1], 'r:gz') as archive:
    lemmas = {}
    for part in ('noun', 'verb', 'adj', 'adv'):
        raw = archive.extractfile(f'WordNet-3.0/dict/index.{part}').read().decode('utf-8')
        for line in raw.splitlines():
            if line and not line.startswith(' '):
                fields = line.split()
                lemma = fields[0].replace('_', ' ')
                lemmas.setdefault(lemma.lower(), {'lemma': lemma, 'part': part, 'offset': fields[-1]})
    license_name = next(member.name for member in archive.getmembers() if member.name == 'WordNet-3.0/LICENSE')
    (DATA / 'WORDNET-LICENSE.txt').write_bytes(archive.extractfile(license_name).read())

decks = {}
evidence = {}
for category, candidates in CANDIDATES.items():
    found, omitted = [], []
    for word in candidates.split():
        if word.lower() in EXCLUDED_WORDS.get(category, set()):
            continue
        if word.lower() in lemmas:
            if word.lower() not in {w.lower() for w in found}:
                found.append(word)
                evidence[word.lower()] = lemmas[word.lower()]
        else:
            omitted.append(word)
    if category != 'everyday':
        assert len(found) >= 70, (category, len(found))
    decks[category] = sorted(found, key=str.lower)
    print(f'{category}: {len(found)} verified; omitted {", ".join(omitted)}')

# Broaden Global beyond objects: familiar actions, qualities, manner and position.
for word in '''accept add agree allow answer arrive ask avoid bake begin believe borrow break bring build buy carry catch celebrate change choose clean climb close collect compare cook copy count cover create cry cut dance decide describe discover divide draw dream drink drive drop earn eat enjoy enter explain explore fall feel find finish fix float fly follow forget forgive freeze gather give grow guess hang happen hear help hide hold hope imagine improve invite join jump keep kick kiss knock laugh learn leave lend lift listen look lose love make meet melt mix move need notice offer open paint park pay plan play point pour practice promise protect pull push put read remember repeat rest return ride ring rise roll run save search see sell send share shout show sing sit sleep slide smile speak spend stand start stay stop study surprise swim take teach tell think throw touch travel try turn understand use visit wait wake walk want wash watch wear whisper win work worry write young old happy sad bright dark brave calm clever kind proud friendly gentle fair honest patient quiet loud sharp smooth soft hard rough sweet bitter salty sour warm cool hot cold wet dry deep shallow wide narrow empty full heavy light quick slow strong weak rich poor early late safe dangerous simple difficult useful ordinary strange beautiful ugly lovely curious careful careless busy lazy lucky fresh stale clear cloudy equal different perfect serious silly wild tame healthy tired awake alive together apart again always never often sometimes soon already almost enough very rather really quite perhaps certainly easily slowly quickly loudly softly quietly happily sadly carefully suddenly usually rarely nearby everywhere nowhere anywhere somewhere upward downward forward backward ahead away home here there today yesterday tomorrow tonight above below before after inside outside near far around across over under through along beyond instead otherwise however therefore meanwhile indeed eventually exactly immediately probably absolutely completely forever twice once'''.split():
    if word in lemmas:
        decks['everyday'].append(word)
        evidence[word] = lemmas[word]

global_words = {}
for words in decks.values():
    for word in words:
        # Capitalized geography candidates are proper place names. Keep them in
        # Geography; ordinary English senses (e.g. turkey) come from other decks.
        if word == word.lower():
            global_words.setdefault(word.lower(), word)
decks['global'] = sorted(global_words.values(), key=str.lower)
del decks['everyday']
for category, words in decks.items():
    (DATA / f'{category}.json').write_text(json.dumps(words, ensure_ascii=False, indent=2) + '\n')
(DATA / 'words.js').write_text('// Generated from the neighboring JSON decks by tools/prepare_words.py.\n// Princeton WordNet 3.0; see WORDNET-LICENSE.txt and SOURCES.md.\nwindow.PyramidWords = ' + json.dumps(decks, ensure_ascii=False) + ';\n')
(DATA / 'wordnet-evidence.json').write_text(json.dumps(evidence, indent=2) + '\n')
print(f'Global: {len(decks["global"])} unique words. All decks verified against WordNet 3.0.')
